### ISSUE TITLE
Only ItemTemplate is installed via NuGet package

### ISSUE THREAD

**Issue by Kralizek** [tintoy/dotnet-template-templates#5]
Installed the package via NuGet by `dotnet new -i FiftyProtons.Templates.DotNetNew::0.1.0-alpha1`, only the ItemTemplate was available when running `dotnet new -l`

![image](https://cloud.githubusercontent.com/assets/2458439/24085118/0cf621e0-0cf6-11e7-8d42-db67258b37ae.png)

**Comment by tintoy** [comment]
Hmm - it doesn't work for me either now! That's odd, I used this only last week. Give me a couple of minutes to have a look.

**Comment by tintoy** [comment]
Looks like the last batch of changes I made has caused problems. I'll get back to you once I've figured out why; sorry for the inconvenience :-(

**Comment by tintoy** [comment]
Ok, @Kralizek I think I've worked it out.

If you run `dotnet new -l` in an empty directory, it only shows project templates, and if you run it in a  non-empty directory, it only shows item templates. If you run `dotnet new project-template` or `dotnet new item-template` it should work even though they are not displayed for some reason. I'll raise an issue in [dotnet/templating](https://github.com/dotnet/templating) to ask why the templates are not visible even though they are usable.

Note that these templates require 1.0.0 (RTM) tooling or newer (RC4 tooling won't work because some features, such as renaming files after copy, were broken).

**Comment by tintoy** [comment]
Also, it seems that the template engine is getting confused between the 2 templates (item and project). I can run either one by name, but only the last one I installed is visible in the list. I'll ask the dotnet guys if they can shed any light on why.

**Comment by Kralizek** [comment]
Tried in an empty folder, project-template still not in the list. when I try `dotnet new project-template` in an empty folder i get

![image](https://cloud.githubusercontent.com/assets/2458439/24085369/2997adaa-0cfb-11e7-9ea9-3af8a6b8e396.png)

**Comment by tintoy** [comment]
Ok, that's odd - it works for me but I am running from source. I've got a meeting in 5 mins, but I'll try and clean out my cache and install the package to test after that. Again, sorry for the inconvenience and thanks for your patience :)

**Comment by Kralizek** [comment]
No problem =) glad to help.

**Comment by tintoy** [comment]
In the meanwhile, could you try cleaning out your template cache and running:

```
dotnet new -i src/Templates/content/ProjectTemplate
dotnet new -i src/Templates/content/ItemTemplate
```

Will be interesting to see if it works when run from source (it did for me)...

**Comment by Kralizek** [comment]
How to clear the template cache?

**Comment by tintoy** [comment]
Just remove the `%userprofile%\.templateengine` (windows) or `~/.templateengine` (Linux / OSX) directory.

**Comment by tintoy** [comment]
BTW, I've reported this via dotnet/templating#443.

**Comment by tintoy** [comment]
Ok @Kralizek this should be working now (see dotnet/templating#443 for details).

Just fetch the latest source or install version `0.1-alpha4`.
